### ISSUE TITLE
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).

### ISSUE THREAD

**Issue by gour** [januschung/math-worksheet-generator#43]
Hello,

very nice and useful package to quickly generate worksheets for children practising basis math!

However, I've problem generating worksheets for division...

```
$ python3 run.py --type / --digits 3 -q 10
Traceback (most recent call last):
  File "/home/gour/repos/external/math-worksheet-generator/run.py", line 285, in <module>
    main(args.type, size_, args.question_count, args.output)
  File "/home/gour/repos/external/math-worksheet-generator/run.py", line 237, in main
    seed_question = new_pdf.get_list_of_questions(question_count)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gour/repos/external/math-worksheet-generator/run.py", line 88, in get_list_of_questions
    new_question = self.generate_question()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gour/repos/external/math-worksheet-generator/run.py", line 74, in generate_question
    num_1, num_2, answer = self.division_helper(num_1)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gour/repos/external/math-worksheet-generator/run.py", line 49, in division_helper
    factor = random.sample(self.factors(num), 1)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/random.py", line 436, in sample
    raise TypeError("Population must be a sequence.  "
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

Any hint?

**Comment by januschung** [comment]
Sorry for the late response but I cannot reproduce the problem.

**Comment by gour** [comment]
It looks it was some python-related issued. Now I get:

```
$ python3 run.py --type / --digits 3 -q 10
/home/gour/repos/external/math-worksheet-generator/run.py:49: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  factor = random.sample(self.factors(num), 1)[0]
```

with `Python 3.10.9` ?

**Comment by januschung** [comment]
Please try using python 3.7

**Comment by princeofdream** [comment]
change random.sample(self.factors(num), 1)[0] to random.sample(list(self.factors(num)), 1)[0]

**Comment by januschung** [comment]
Thanks so much @princeofdream and @gour . I shall have spent some time troubleshooting your problem and hope it is not too late.
